### ISSUE TITLE
tts-multi-engines

### ISSUE THREAD

**Issue by tvraman** [robertmeta/sharpwin#2]
push values on to this variable only after you load emacspeak-setup, otherwise that will throw an error

**Comment by robertmeta** [comment]
Will do, I had incorrectly assumed it had to exist when the dtk-initialize was called to start the notify server.

**Comment by tvraman** [comment]
the bug is that you're calling (require 'emacspeak-setup) *after* you do
the push, so that var tts-multi-engines is not yet defined.
dtk-initialize happens after you load emacspeak-setup which starts
emacspeak -- function emacspeak calls dtk-initialize

--

**Comment by robertmeta** [comment]
Yep, going to make a small PR to add the multi-engine and the sharpwin to the list of servers and just tell people to use the git version as well in the readme.
