### ISSUE TITLE
make.ps1 will prove unmaintainable

### ISSUE THREAD

**Issue by tvraman** [robertmeta/sharpwin#4]
assume all the dances in make.ps1 are  just  transitionary  it'll prove unmaintainable  otherwise

**Comment by robertmeta** [comment]
That is an open-problem I will bring up on the list.  I don't actually have a well throught out solution for that yet.

**Comment by tvraman** [comment]
Thoughts:

1. The make file there should only concern itself with building the
   sharpwin server.
2. The regular emacspeak Makefile should be building the .elc files with
   *no* changes for windows.

   
--

**Comment by robertmeta** [comment]
1. No problem. 

2. This is what I am hoping the list has ideas on, right now the 
root makefile WILL NOT work on windows, even some of the concepts 
don't map well, chmod 755 doesn't really map to an ACL. 

Some harmless changes would help, changing quotes in two places 
which impacts nothing as there is nothing relevantly escaped in 
them. 

I will continue to think on #2. 

> On Apr 13, 2024, at 18:01, T. V. Raman ***@***.***> wrote:
> 
> 
> Thoughts:
> 
> 1. The make file there should only concern itself with building the
> sharpwin server.
> 2. The regular emacspeak Makefile should be building the .elc files with
> *no* changes for windows.
> 
> 
> -- 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by robertmeta** [comment]
OK, posted to the list, got a solution I love.  Works great, no changes.  Converting to makefile now.

**Comment by tvraman** [comment]
For now this is a *hard* requirement:

There should  be no if-windows -- or for that matter, any if-platform
 checks in any Makefile except for the Makefile in server directories,
 and that only if the server builds on multiple platforms.
 
--

**Comment by robertmeta** [comment]
Yep, already done. 

> On Apr 13, 2024, at 22:13, T. V. Raman ***@***.***> wrote:
> 
> 
> For now this is a *hard* requirement:
> 
> There should be no if-windows -- or for that matter, any if-platform
> checks in any Makefile except for the Makefile in server directories,
> and that only if the server builds on multiple platforms.
> 
> -- 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>

--
Robert Melton
***@***.***
